### ISSUE TITLE
Reconnect interval?

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-twoloox-pandorasbox#2]
https://github.com/bitfocus/companion-module-christie-pandorasbox/blob/aef7f568a61f7144d29017df068ea33f3de8f6f4/christie-pandorasbox.js#L157

Hi,

I can see that you have added support for setting the reconnect interval of the tcp module. Is there a specific reason for this? This is usually not a user configurable thing.

**Comment by kaminskihub** [comment]
updated
