### ISSUE TITLE
PB nextq dynamic variables not showing time to cue

### ISSUE THREAD

**Issue by nickdiacre** [bitfocus/companion-module-twoloox-pandorasbox#6]
Other sequence time variables are giving feedback, but the nextq times are not...

**Comment by kaminskihub** [comment]
hmm, that is strange. Do you have Cues on your timeline? Please give me a few more details.

**Comment by nickdiacre** [comment]
my bad, sequence wasn't selected for cues... apologies

**Comment by kaminskihub** [comment]
No Problem. Is everything else working for you? Are you also using the Widget Designer Module?

**Comment by nickdiacre** [comment]
no tbf companion is doing everything i would be using widget for...

**Comment by nickdiacre** [comment]
but yes everything else is working good!
